language: objective-c

script: xcodebuild test -project Calculator.xcodeproj -scheme CalculatorTests -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3' -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES -enableCodeCoverage YES

#script: xcodebuild -project Calculator.xcodeproj -scheme CalculatorTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES

# script: 
#  - xctool -project Calculator.xcodeproj -scheme CalculatorTests build test -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
osx_image: xcode8.2
after_success: slather
#- bash <(curl -s https://codecov.io/bash)  -J 'Calculator'

